/*
 * This source file was generated by the Gradle 'init' task
 */

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        Scanner s = new Scanner(System.in);
        List<Pessoa> lista = new ArrayList<>();
        int menu = 0;

        while (menu!= 5){
            System.out.println("digite 1 pra cadastrar uma pessoa");
            System.out.println("digite 5 para sair");
            menu = s.nextInt();
        }
        if (menu == 1){
            System.out.println("Nome: ");
            String nome = s.nextLine();

            System.out.println("Altura: ");
            double altura = s.nextDouble();

            System.out.println("Idade: ");
            int idade = s.nextInt();

            System.out.println("Peso: ");
            double peso = s.nextDouble();

            Pessoa p = new Pessoa(nome,altura,idade,peso);
            lista.add(p);
        }
        s.close();






    }
}
